name       : onionshare
version    : '2.2'
release    : 5
source     :
    - https://github.com/micahflee/onionshare/archive/v2.2.tar.gz : 7173863d7582b05aa8fd0d2207236e3cbbb38d854aad65e3b98ec5baad521fc2
license    : GPL-3.0-or-later
component  : network.util
summary    : Lets you securely and anonymously share a file of any size with someone
description: |
    OnionShare lets you securely and anonymously share files of any size. It works by starting a web server, making it accessible as a Tor Onion Service, and generating an unguessable URL to access and download the files. It does not require setting up a separate server or using a third party file-sharing service. You host the files on your own computer and use a Tor Onion Service to make it temporarily accessible over the internet. The receiving user just needs to open the URL in Tor Browser to download the file.
rundeps    :
    - flask-httpauth
    - python-pysocks
    - python-qtpy
    - python-requests
    - python-stem
    - python3-pycryptodome
    - tor
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 install/onionshare80.xpm $installdir/usr/share/pixmaps/onionshare80.xpm
