name       : onionshare
version    : '2.0'
release    : 4
source     :
    - https://github.com/micahflee/onionshare/archive/v2.0.tar.gz : 528ceb6234ecacabe51080e351c2e8f205cbf08cdfcfddc418586d578baa030e
license    : GPL-3.0-or-later
component  : network.util
summary    : Lets you securely and anonymously share a file of any size with someone
description: |
    OnionShare lets you securely and anonymously share files of any size. It works by starting a web server, making it accessible as a Tor Onion Service, and generating an unguessable URL to access and download the files. It does not require setting up a separate server or using a third party file-sharing service. You host the files on your own computer and use a Tor Onion Service to make it temporarily accessible over the internet. The receiving user just needs to open the URL in Tor Browser to download the file.
rundeps    :
    - flask
    - python-pysocks
    - python-qtpy
    - python-requests
    - python-stem
    - python3-pycryptodome
    - tor
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 install/onionshare.desktop $installdir/usr/share/applications/onionshare.desktop
    install -Dm00644 install/onionshare80.xpm $installdir/usr/share/pixmaps/onionshare80.xpm